package invision

data class ClassMapping(val id: Int, var name: String, val autoGenerated: Boolean=true, var packageName: String?)

class ClassMap {
    val classList = mutableListOf<ClassMapping>()
    fun get(id: Int) : ClassMapping? {
        classList.forEach {
            if (it.id == id) {
                return it
            }
        }
        return null
    }

    fun getName(id: Int) : String {
        return get(id)?.name?:""
    }
}